// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamecenter.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 要定義你Request & Res的Struct
type TestRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_7aff33d9480054f3, []int{0}
}
func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (dst *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(dst, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

type TestReply struct {
	State                string   `protobuf:"bytes,1,opt,name=State,json=state" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestReply) Reset()         { *m = TestReply{} }
func (m *TestReply) String() string { return proto.CompactTextString(m) }
func (*TestReply) ProtoMessage()    {}
func (*TestReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_7aff33d9480054f3, []int{1}
}
func (m *TestReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestReply.Unmarshal(m, b)
}
func (m *TestReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestReply.Marshal(b, m, deterministic)
}
func (dst *TestReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestReply.Merge(dst, src)
}
func (m *TestReply) XXX_Size() int {
	return xxx_messageInfo_TestReply.Size(m)
}
func (m *TestReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TestReply.DiscardUnknown(m)
}

var xxx_messageInfo_TestReply proto.InternalMessageInfo

func (m *TestReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type CreateGameRequest struct {
	GameType             string   `protobuf:"bytes,1,opt,name=GameType,json=gameType" json:"GameType,omitempty"`
	GameID               int32    `protobuf:"varint,2,opt,name=GameID,json=gameID" json:"GameID,omitempty"`
	Players              *Players `protobuf:"bytes,3,opt,name=Players,json=players" json:"Players,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameRequest) Reset()         { *m = CreateGameRequest{} }
func (m *CreateGameRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGameRequest) ProtoMessage()    {}
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_7aff33d9480054f3, []int{2}
}
func (m *CreateGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameRequest.Unmarshal(m, b)
}
func (m *CreateGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameRequest.Marshal(b, m, deterministic)
}
func (dst *CreateGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameRequest.Merge(dst, src)
}
func (m *CreateGameRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGameRequest.Size(m)
}
func (m *CreateGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameRequest proto.InternalMessageInfo

func (m *CreateGameRequest) GetGameType() string {
	if m != nil {
		return m.GameType
	}
	return ""
}

func (m *CreateGameRequest) GetGameID() int32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *CreateGameRequest) GetPlayers() *Players {
	if m != nil {
		return m.Players
	}
	return nil
}

type Players struct {
	PlayerList           []*Player `protobuf:"bytes,1,rep,name=PlayerList,json=playerList" json:"PlayerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Players) Reset()         { *m = Players{} }
func (m *Players) String() string { return proto.CompactTextString(m) }
func (*Players) ProtoMessage()    {}
func (*Players) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_7aff33d9480054f3, []int{3}
}
func (m *Players) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Players.Unmarshal(m, b)
}
func (m *Players) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Players.Marshal(b, m, deterministic)
}
func (dst *Players) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Players.Merge(dst, src)
}
func (m *Players) XXX_Size() int {
	return xxx_messageInfo_Players.Size(m)
}
func (m *Players) XXX_DiscardUnknown() {
	xxx_messageInfo_Players.DiscardUnknown(m)
}

var xxx_messageInfo_Players proto.InternalMessageInfo

func (m *Players) GetPlayerList() []*Player {
	if m != nil {
		return m.PlayerList
	}
	return nil
}

type Player struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	UUID                 string   `protobuf:"bytes,2,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,json=name" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_7aff33d9480054f3, []int{4}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Player) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateGameReply struct {
	State                string   `protobuf:"bytes,1,opt,name=State,json=state" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameReply) Reset()         { *m = CreateGameReply{} }
func (m *CreateGameReply) String() string { return proto.CompactTextString(m) }
func (*CreateGameReply) ProtoMessage()    {}
func (*CreateGameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_7aff33d9480054f3, []int{5}
}
func (m *CreateGameReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameReply.Unmarshal(m, b)
}
func (m *CreateGameReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameReply.Marshal(b, m, deterministic)
}
func (dst *CreateGameReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameReply.Merge(dst, src)
}
func (m *CreateGameReply) XXX_Size() int {
	return xxx_messageInfo_CreateGameReply.Size(m)
}
func (m *CreateGameReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameReply proto.InternalMessageInfo

func (m *CreateGameReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "api.TestRequest")
	proto.RegisterType((*TestReply)(nil), "api.TestReply")
	proto.RegisterType((*CreateGameRequest)(nil), "api.CreateGameRequest")
	proto.RegisterType((*Players)(nil), "api.Players")
	proto.RegisterType((*Player)(nil), "api.Player")
	proto.RegisterType((*CreateGameReply)(nil), "api.CreateGameReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameCenterClient is the client API for GameCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameCenterClient interface {
	// Request & Res都要寫，不可空
	Ping(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error)
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameReply, error)
}

type gameCenterClient struct {
	cc *grpc.ClientConn
}

func NewGameCenterClient(cc *grpc.ClientConn) GameCenterClient {
	return &gameCenterClient{cc}
}

func (c *gameCenterClient) Ping(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error) {
	out := new(TestReply)
	err := c.cc.Invoke(ctx, "/api.GameCenter/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameReply, error) {
	out := new(CreateGameReply)
	err := c.cc.Invoke(ctx, "/api.GameCenter/CreateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameCenterServer is the server API for GameCenter service.
type GameCenterServer interface {
	// Request & Res都要寫，不可空
	Ping(context.Context, *TestRequest) (*TestReply, error)
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameReply, error)
}

func RegisterGameCenterServer(s *grpc.Server, srv GameCenterServer) {
	s.RegisterService(&_GameCenter_serviceDesc, srv)
}

func _GameCenter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameCenterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameCenter/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameCenterServer).Ping(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameCenter_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameCenterServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameCenter/CreateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameCenterServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GameCenter",
	HandlerType: (*GameCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GameCenter_Ping_Handler,
		},
		{
			MethodName: "CreateGame",
			Handler:    _GameCenter_CreateGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gamecenter.proto",
}

func init() { proto.RegisterFile("gamecenter.proto", fileDescriptor_gamecenter_7aff33d9480054f3) }

var fileDescriptor_gamecenter_7aff33d9480054f3 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0xfd, 0xf2, 0xdb, 0xe6, 0xe6, 0xb3, 0xd6, 0x4b, 0x29, 0xa1, 0xab, 0x38, 0x0b, 0x0d, 0x0a,
	0x5d, 0x54, 0x70, 0xe5, 0x42, 0x6c, 0x41, 0x0b, 0x45, 0xca, 0xd8, 0xe2, 0x7a, 0x94, 0x4b, 0x08,
	0x34, 0xc9, 0x98, 0x4c, 0x85, 0xbc, 0x8e, 0x4f, 0x2a, 0x99, 0xc4, 0x1a, 0x28, 0xee, 0xee, 0xf9,
	0x23, 0x27, 0x67, 0x60, 0x18, 0x8b, 0x94, 0xde, 0x29, 0x53, 0x54, 0x4c, 0x65, 0x91, 0xab, 0x1c,
	0x2d, 0x21, 0x13, 0x76, 0x02, 0xfe, 0x86, 0x4a, 0xc5, 0xe9, 0x63, 0x4f, 0xa5, 0x62, 0xe7, 0xe0,
	0x35, 0x50, 0xee, 0x2a, 0x1c, 0x81, 0xf3, 0xa2, 0x84, 0xa2, 0xc0, 0x08, 0x8d, 0xc8, 0xe3, 0x4e,
	0x59, 0x03, 0x96, 0xc3, 0xd9, 0xbc, 0x20, 0xa1, 0xe8, 0x51, 0xa4, 0xd4, 0xe6, 0x70, 0x02, 0xfd,
	0x1a, 0x6e, 0x2a, 0xf9, 0xe3, 0xee, 0xc7, 0x2d, 0xc6, 0x31, 0xb8, 0xb5, 0xb6, 0x5c, 0x04, 0x66,
	0x68, 0x44, 0x0e, 0x77, 0x63, 0x8d, 0xf0, 0x02, 0x7a, 0xeb, 0x9d, 0xa8, 0xa8, 0x28, 0x03, 0x2b,
	0x34, 0x22, 0x7f, 0xf6, 0x7f, 0x2a, 0x64, 0x32, 0x6d, 0x39, 0xde, 0x93, 0xcd, 0xc1, 0x6e, 0x0f,
	0x3e, 0xbc, 0x06, 0x68, 0xce, 0x55, 0x52, 0xaa, 0xc0, 0x08, 0xad, 0xc8, 0x9f, 0xf9, 0x9d, 0x14,
	0x07, 0x79, 0x90, 0xd9, 0x3d, 0xb8, 0x0d, 0x8b, 0x03, 0x30, 0x97, 0x0b, 0xdd, 0xcb, 0xe1, 0x66,
	0xb2, 0x40, 0x04, 0x7b, 0xbb, 0x6d, 0xfb, 0x78, 0xdc, 0xde, 0x6f, 0x97, 0x9a, 0x7b, 0x16, 0x29,
	0xe9, 0x2a, 0x1e, 0xb7, 0x33, 0x91, 0x12, 0xbb, 0x84, 0xd3, 0xee, 0xaf, 0xfe, 0xb9, 0xc9, 0xec,
	0x13, 0xa0, 0xb6, 0xcc, 0xf5, 0xbc, 0x78, 0x05, 0xf6, 0x3a, 0xc9, 0x62, 0x1c, 0xea, 0x66, 0x9d,
	0x79, 0x27, 0x83, 0x0e, 0x23, 0x77, 0x15, 0xfb, 0x87, 0x77, 0x00, 0xbf, 0x9f, 0xc0, 0xb1, 0xd6,
	0x8f, 0xe6, 0x9d, 0x8c, 0x8e, 0x78, 0x9d, 0x7e, 0x70, 0xbf, 0x4c, 0xeb, 0x69, 0xf5, 0xfa, 0xe6,
	0xea, 0x17, 0xbd, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x03, 0xe6, 0x9c, 0x3b, 0xe5, 0x01, 0x00,
	0x00,
}
